# Generated by Django 2.2.6 on 2019-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, default='../static/musictimeapp/images/default-profile-pic.jpg', max_length=200),
        ),
    ]
