# Generated by Django 2.2.6 on 2019-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musictimeapp', '0003_auto_20191020_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
