# Generated by Django 2.2.6 on 2019-10-21 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musictimeapp', '0005_auto_20191020_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(related_name='followers', through='musictimeapp.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
        model_name='customuser',
        name='follows',
        field=models.ManyToManyField(related_name='followers', through='Follow', to='customuser'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_is_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
