# Generated by Django 2.2.6 on 2019-10-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musictimeapp', '0007_auto_20191023_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=40)),
                ('studio_details', models.TextField()),
                ('studio_type', models.CharField(choices=[('rehearsal_space', 'Rehearsal Space'), ('podcast_space', 'Podcast Space'), ('home_studio', 'Home Studio'), ('mid_level_studio', 'Mid-Level-Studio'), ('top_line_studio', 'Top-Line-Studio')], default='rehearsal_space', max_length=20)),
                ('past_clients', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_samples', models.CharField(max_length=200)),
                ('equipments', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(max_length=200)),
                ('price_per_hour', models.FloatField()),
                ('studio_image', models.ImageField(upload_to='studio_images/')),
                ('studio_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
